name: spikeinterface
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - hdbscan=0.8.39=py311h17033d2_1
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libopenblas=0.3.30=pthreads_ha4fe6b2_2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - numpy=2.3.4=py311h80b3fa1_0
  - openssl=3.5.4=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python_abi=3.11=2_cp311
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.2=py311h9a1c30b_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asciitree==0.3.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - autopep8==2.3.2
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.1
      - cuda-python==13.0.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - distinctipy==1.3.4
      - faiss-cpu==1.12.0
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - intel-openmp==2021.4.0
      - ipykernel==7.0.1
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kilosort==4.1.1
      - kiwisolver==1.4.9
      - lark==1.3.0
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mistune==3.1.4
      - mkl==2021.4.0
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - neo==0.14.3
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numcodecs==0.15.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prettytable==3.16.0
      - probeinterface==0.3.0
      - prometheus-client==0.23.1
      - psutil==7.1.1
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.0
      - pyqt6-sip==13.10.2
      - pyqtgraph==0.13.7
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtpy==2.4.3
      - quantities==0.16.2
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - send2trash==1.8.3
      - six==1.17.0
      - skops==0.13.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spikeinterface==0.103.0
      - sympy==1.14.0
      - tbb==2021.11.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.9.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - wrapt==1.17.3
      - zarr==2.18.7
prefix: C:\Users\ryoi\AppData\Local\anaconda3\envs\spikeinterface
